fix ident

diff --git a/.github/workflows/qiita-ci.yml b/.github/workflows/qiita-ci.yml
--- a/.github/workflows/qiita-ci.yml
+++ b/.github/workflows/qiita-ci.yml
@@ -42,27 +42,29 @@ jobs:
           auto-update-conda: true
           python-version: 3.6
 
-    - name: Run a multi-line script
-      shell: bash -l {0}
-      run: |
-        # 7. Setting up SSH
-        #    modified from: https://stackoverflow.com/a/60367309
-        ssh-keygen -t rsa -C "ssh test key" -f $PWD/qiita_ware/test/test_data/test_key -P ""
-        mkdir ~/.ssh/
-        mv $PWD/qiita_ware/test/test_data/test_key.pub ~/.ssh/
-        cat > ~/.ssh/config <<EOF
-          Host host.example
-           User $USER
-           HostName 127.0.0.1
-           IdentityFile ~/.ssh/test_key
-        EOF
-        echo -n 'from="127.0.0.1" ' | cat - ~/.ssh/test_key.pub > ~/.ssh/authorized_keys
-        ssh -o 'StrictHostKeyChecking no' host.example id || echo "ssh failed as expected... trying to fix permissions"
-        chmod og-rw ~
-        echo "After fixing permissions on home folder ~ ..."
-        ls -la ~/.ssh
-        ssh -o 'StrictHostKeyChecking no' host.example id
-        scp -i $PWD/qiita_ware/test/test_data/test_key localhost:$PWD/qiita_ware/test/test_data/random_key $PWD/qiita_ware/test/test_data/random_key_copy
+
+      - name: Run a multi-line script
+        shell: bash -l {0}
+        run: |
+          # 7. Setting up SSH
+          #    modified from: https://stackoverflow.com/a/60367309
+          ssh-keygen -t rsa -C "ssh test key" -f $PWD/qiita_ware/test/test_data/test_key -P ""
+          mkdir ~/.ssh/
+          mv $PWD/qiita_ware/test/test_data/test_key.pub ~/.ssh/
+          cat > ~/.ssh/config <<EOF
+            Host host.example
+             User $USER
+             HostName 127.0.0.1
+             IdentityFile ~/.ssh/test_key
+          EOF
+          echo -n 'from="127.0.0.1" ' | cat - ~/.ssh/test_key.pub > ~/.ssh/authorized_keys
+          ssh -o 'StrictHostKeyChecking no' host.example id || echo "ssh failed as expected... trying to fix permissions"
+          chmod og-rw ~
+          echo "After fixing permissions on home folder ~ ..."
+          ls -la ~/.ssh
+          ssh -o 'StrictHostKeyChecking no' host.example id
+          scp -i $PWD/qiita_ware/test/test_data/test_key localhost:$PWD/qiita_ware/test/test_data/random_key $PWD/qiita_ware/test/test_data/random_key_copy
+
 
       - name: Basic dependencies install
         shell: bash -l {0}
